"use client";
import React from "react";
import Head from "next/head";

const PrivacyPolicy = () => {
  return (
    <div className="min-h-screen bg-black text-white">
      <Head>
        <title>Privacy Policy - Soulsoft Infotech Pvt. Ltd</title>
        <meta
          name="description"
          content="Privacy Policy for Soulsoft Infotech Pvt. Ltd"
        />
      </Head>

      <div className="container mx-auto px-4 py-8">
        <h1 className="text-3xl font-bold mb-6">Privacy Policy</h1>
        <p className="mb-4">Last updated: August 10, 2024</p>

        <p className="mb-4">
          This Privacy Policy describes our policies and procedures on the
          collection, use, and disclosure of your information when you use the
          Service, and tells you about your privacy rights and how the law
          protects you.
        </p>

        <p className="mb-4">
          We use your personal data to provide and improve the Service. By
          using the Service, you agree to this Privacy Policy’s collection and
          use of information.
        </p>

        <h2 className="text-2xl font-semibold mt-8 mb-4">
          Interpretation and Definitions
        </h2>

        <h3 className="text-xl font-medium mt-6 mb-2">Interpretation</h3>
        <p className="mb-4">
          The words whose initial letter is capitalized have meanings defined
          under the following conditions. The following definitions shall have
          the same meaning regardless of whether they appear singular or
          plural.
        </p>

        <h3 className="text-xl font-medium mt-6 mb-2">Definitions</h3>
        <p className="mb-4">For this Privacy Policy:</p>
        <ul className="list-disc list-inside mb-4">
          <li>
            <strong>Account:</strong> A unique account created for you to access
            our Service or parts of our Service.
          </li>
          <li>
            <strong>Affiliate:</strong> An entity that controls, is controlled
            by, or is under common control with a party, where “control” means
            ownership of 50% or more of the shares, equity interest, or other
            securities entitled to vote for the election of directors or other
            managing authority.
          </li>
          <li>
            <strong>Cookies:</strong> Small files that are placed on your
            computer, mobile device, or any other device by a website,
            containing the details of your browsing history on that website
            among its many uses.
          </li>
          <li>
            <strong>Country:</strong> Refers to Maharashtra, India.
          </li>
          <li>
            <strong>Device:</strong> Any device that can access the Service,
            such as a computer, cellphone, or a digital tablet.
          </li>
          <li>
            <strong>Personal Data:</strong> Any information that relates to an
            identified or identifiable individual.
          </li>
          <li>
            <strong>Service:</strong> Refers to the Website.
          </li>
          <li>
            <strong>Service Provider:</strong> Any natural or legal person who
            processes the data on behalf of the Company. It refers to
            third-party companies or individuals employed by the Company to
            facilitate the Service, to provide the Service on behalf of the
            Company, to perform services related to the Service, or to assist
            the Company in analyzing how the Service is used.
          </li>
          <li>
            <strong>Usage Data:</strong> Data collected automatically, either
            generated by the use of the Service or from the Service
            infrastructure itself (for example, the duration of a page visit).
          </li>
          <li>
            <strong>Website:</strong> Refers to Soulsoft, accessible from
            [Soulsoft Website].
          </li>
          <li>
            <strong>You:</strong> The individual accessing or using the
            Service, or the company, or other legal entity on behalf of which
            such individual is accessing or using the Service, as applicable.
          </li>
        </ul>

        <h2 className="text-2xl font-semibold mt-8 mb-4">
          Collecting and Using Your Data
        </h2>

        <h3 className="text-xl font-medium mt-6 mb-2">Types of Data Collected</h3>
        <p className="mb-4">
          While using our Service, we may ask you to provide us with certain
          personally identifiable information that can be used to contact or
          identify you. Personally identifiable information may include, but is
          not limited to:
        </p>
        <ul className="list-disc list-inside mb-4">
          <li>Email address</li>
          <li>First name and last name</li>
          <li>Phone number</li>
          <li>Address, State, Province, ZIP/Postal code, City</li>
          <li>Usage Data</li>
        </ul>

        <h3 className="text-xl font-medium mt-6 mb-2">Usage Data</h3>
        <p className="mb-4">
          Usage Data is collected automatically when using the Service. Usage
          Data may include information such as your device’s Internet Protocol
          address (e.g., IP address), browser type, browser version, the pages
          of our Service that you visit, the time and date of your visit, the
          time spent on those pages, unique device identifiers, and other
          diagnostic data.
        </p>

        <h2 className="text-2xl font-semibold mt-8 mb-4">
          Tracking Technologies and Cookies
        </h2>
        <p className="mb-4">
          We use Cookies and similar tracking technologies to track the
          activity on our Service and store certain information. Tracking
          technologies used are beacons, tags, and scripts to collect and track
          information and to improve and analyze our Service.
        </p>

        <h2 className="text-2xl font-semibold mt-8 mb-4">
          Use of Your Personal Data
        </h2>
        <p className="mb-4">
          The Company may use Personal Data for the following purposes:
        </p>
        <ul className="list-disc list-inside mb-4">
          <li>To provide and maintain our Service.</li>
          <li>To manage your account and registration as a user.</li>
          <li>To contact you via email, phone, or other communication methods.</li>
          <li>To provide you with news, offers, and updates.</li>
          <li>For business transfers or legal obligations.</li>
        </ul>

        <h2 className="text-2xl font-semibold mt-8 mb-4">
          Retention of Your Personal Data
        </h2>
        <p className="mb-4">
          The Company will retain your Personal Data only for as long as is
          necessary for the purposes set out in this Privacy Policy.
        </p>

        <h2 className="text-2xl font-semibold mt-8 mb-4">
          Security of Your Personal Data
        </h2>
        <p className="mb-4">
          The security of your Personal Data is important to us, but no method
          of transmission over the Internet is 100% secure.
        </p>

        <h2 className="text-2xl font-semibold mt-8 mb-4">
          Changes to This Privacy Policy
        </h2>
        <p className="mb-4">
          We may update our Privacy Policy from time to time. You are advised
          to review this Privacy Policy periodically for any changes.
        </p>
      </div>
    </div>
  );
};

export default PrivacyPolicy;